import {StyleSheet, Platform} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  mainHeader: {
    height: 58,
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'red',
  },
  homeMain: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerContainer: {
    width: 50,
    // backgroundColor: 'blue',
    alignItems: 'center',
    justifyContent: 'center',
  },
  flatlist_container: {
    width: wp(90),
    height: wp(40),
    backgroundColor: '#FFFFFF',
    elevation: 2,
    marginTop: wp(2),
    alignSelf: 'center',
    borderRadius: 10,
    flexDirection: 'row',
    marginBottom: 10,
    alignItems: 'center',
  },
  product_imgView: {
    width: wp(38),
    height: hp(17),
    backgroundColor: '#FBFBFB',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    left: wp(1),
  },
  Cart_Image: {
    width: wp(36),
    height: wp(38),
    borderRadius: 10,
  },
  Home_txt3: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 14,
  },
  Home_txt4: {
    color: '#8B98B4',
    fontSize: 14,
    right: 4,
    marginTop: 2,
  },
  Home_txt5: {
    color: '#000',
    width: wp(45),
    marginTop: 10,
    fontSize: 14,
  },
  addCart_button: {
    width: wp(12),
    height: wp(12),
    borderRadius: 30,
    backgroundColor: '#F5F5F5',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: wp(2),
  },
  PriceName_View: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: wp(10),
    top: wp(10),
  },
  Detail_txt1: {
    fontSize: 16,
    color: '#000',
  },
  detail_img: {
    width: wp(100),
    height: hp(30),
    alignSelf: 'center',
  },
  Detail_txt2: {
    fontSize: 14,
    color: '#000',
    paddingLeft: wp(10),
  },
  line: {
    borderBottomWidth: 3,
    width: 80,
    borderBottomColor: '#8B98B4',
    marginBottom: 10,
    top: 6,
    left: wp(10),
  },
  Detail_txt3: {
    fontWeight: 'bold',
    fontSize: 14,
    color: 'black',

    marginTop: wp(8),
    marginHorizontal: wp(9),
    lineHeight: 22,
  },
  mainView: {
    width: wp(100),
    flex: 1,
    // height: hp(88.5),
    backgroundColor: 'white',
    // borderBottomLeftRadius: 30,
    // borderBottomRightRadius: 30,
  },
  flatlistCart_container: {
    width: wp(90),
    // height: hp(16),
    backgroundColor: '#FFFFFF',
    elevation: 3,
    marginTop: hp(1),
    alignSelf: 'center',
    paddingBottom: 10,

    borderRadius: 10,
    flexDirection: 'row',
    marginBottom: 10,
    // alignItems:'center'
  },
  product_imgView: {
    width: wp(38),
    height: hp(17),
    backgroundColor: '#FBFBFB',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    left: wp(1),
  },
  Home_txt4: {
    color: '#8B98B4',
    // fontFamily: 'Montserrat-Regular',
    fontSize: 14,
    right: 4,
    marginTop: 2,
  },
  minus_button: {
    width: wp(6),
    height: wp(6),
    backgroundColor: '#556B2F',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
  },
  categoryStyle: {
    height: 30,
    borderWidth: 1,
    justifyContent: 'center',
    borderColor: '#ccc',
    paddingHorizontal: 15,
    margin: 7,
    borderRadius: 15,
  },
});
